# fly.toml app configuration file generated for zenithwave-bot on 2026-03-27T23:35:43+08:00

app = 'zenithwave-bot'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
